[build]
    functions = "functions"
    command = "CI= npm run build"
    publish = "build"
    environment = { CHROME_WS_ENDPOINT = "ws://Applications/Chromium.app/Contents/MacOS/Chromium" }

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/data/*"]

[context.production.environment]
    NODE_ENV = "production"