[build]
    functions = "functions"
    command = "CI= npm run build"
    publish = "build"

[context.production]
  [context.production.environment]
    NETLIFY_SITE_ID = "f11d77d1-1246-43f0-bdea-1e60b0ff7aed"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NETLIFY_SITE_ID = "f11d77d1-1246-43f0-bdea-1e60b0ff7aed"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NETLIFY_SITE_ID = "f11d77d1-1246-43f0-bdea-1e60b0ff7aed"