[build]
    functions = "functions"
    command = "CI= npm run build"
    publish = "build"

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/data/cookies/cookie.json", "functions/data/chromium/**"]
  external_node_modules = ["@sparticuz/chromium"]

[context.production.environment]
    NODE_ENV = "production"

[context.development.environment]
    NODE_ENV = "development"
