[build]
    functions = "functions"
    command = "CI= npm run build"
    publish = "build"

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/data/cookies/cookie.json", "functions/data/chromium/**"]
  external_node_modules = ["@sparticuz/chromium"]

[context.production.environment]
    NODE_ENV = "production"
    PUPPETEER_EXECUTABLE_PATH = "/opt/homebrew/bin/chromium"

[[plugins]]
package = "netlify-plugin-inline-functions-env"
package = "@netlify/plugin-chromium"