[build]
    functions = "functions"
    command = "CI= npm run build"
    publish = "build"

[build.environment]
  NODE_ENV = "production"    # Sets the Node environment to 'production'
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"   # Tells Puppeteer not to download Chromium during build

[functions]
  node_bundler = "esbuild"
  included_files = ["functions/data/*"]

[context.production.environment]
    NODE_ENV = "production"